README.md
=> Add BoltAI and PDF Pals

README.md
=> Added hiretool.io

README.md
Dan thanks for doing this, you are the best ❤️❤️
Best Deeps!
=> Add subreddit tracker

README.md
=> added uptimebeats.com deal

README.md
Added a new entry for Ikigenia in AI Productivity & Learning Tools and cyberBots in troductivity Tools & Services
=> IkigenIA and cyberBots

README.md
=> Add SendBroadcast.net to the list

README.md
=> Add ShipFlutter and Mumble Sort discounts

README.md
Added Shootmail lifetime access deal
=> Added Shootmail lifetime access deal

README.md
=> add technical writing course

README.md
Larafast - Laravel SaaS Starter Kit
=> Laravel - Larafast

README.md
Add Trio Mindful Todo List App  to Rare Big Deals
=> Add Trio to Rare Big Deals

README.md
=> add anotherwrapper

README.md
=> Add BlogToPin

README.md
I think we need another category for FaceScreen.
=> Add Presentify and ToDoBar

README.md
=> gsctool.com & sortpin.com

README.md
=> added wifi money bundle

README.md
=> Add DirectoryFast

README.md
=> Add fastshorts

README.md
=> added Siteshot Pro BF deal

README.md
Adds a new category miscellaneous, since none of the others quite fit. Hope that's ok! Alternatively could be in a research category under learning.
=> Adds My Deals/Miscellaneous

README.md
=> Fix rogue brace

README.md
=> Added oscarstories.com | fragdaspdf.de | branding5.com

README.md
Wrote it in the commit. didn't add hahah
=> Really add fragdaspdf

README.md
=> Updated with BrainDump and VoiceType

README.md
Added my very niche product to the list
I am not sure if it fits the overall vibe though
=> Add AIDevAssess.com

README.md
=> Add Avo for Rails

README.md
=> Add FaceScreen

README.md
Use a different discount code, directly link to discount in gumroad.
=> Update My Deals

README.md
Thanks! Such a great project!!
=> Add CanvasWizard.co to RareBigDeal

README.md
=> Add Stagetimer Lifetime License deal

README.md
=> added deal

README.md
=> Added Cleft Notes to AI Tools/Productivity

README.md
Added shiftapp.com black friday deal!
=> Update README.md add ShiftApp

README.md
Corrected wrong TapRefer link.
=> Corrected https//TapRefer.com to https://TapRefer.com

README.md
Hello Dan, added my app Captionify. Thanks!
=> Added https://captionify.app

README.md
Add Bayview to developer tool deals
=> Add Bayview to developer tool deals

README.md
Hi,
Adding deals for my products MuteDeck and WhatPulse. Thanks!
=> Add MuteDeck & WhatPulse

README.md
Thank you for building this Dan. 
Here is the [ApparenceKit flutter template](https://apparencekit.dev) promotion
=> Add ApparenceKit flutter template promotion

README.md
Usually there's only a yearly and monthly subscription - Lifetime is a black week special
=> Added Capitally to the list

README.md
Hopefully I checked all the boxes from the README. Thanks for curating! 🙏
=> Add LegibleNews.com, Terminalwire.com, TinyZap.com, and Thingybase.com

README.md
Hi @danmindru , thanks for making this.
=> Add PastePal & Codelime

README.md
=> Update README.md - Microlaunch

README.md
https://aisaver.io/
AISaver offers high-quality AI face-swapping services, including video face swap, photo face swap, GIF face swap, and multi-person face swap.
=> Add AISaver - A AI Face Swap tool

README.md
=> 🌈 Add Binsoo - Photo Editor

README.md
QuickWhisper - https://quickwhisper.app
=> Added QuickWhisper to Prodcutivity

README.md
=> Add tally counter

README.md
Added 2 products 
- Fontfex https://apps.apple.com/app/apple-store/id1597034898?pt=570857&mt=8
- Tasky https://apps.apple.com/app/apple-store/id6502542119?pt=570857&mt=8
=> Add Fontflex and Tasky Widget app

README.md
Let your users login to your Wordpress Elementor site with their favorite social accounts. Add Login with Google, Facebook, Linkedin, Instagram, Github and more with [Happy Social Login](https://wpfolk.com/plugins/happy-social-login). Use coupon code **BFCM50** to get flat 50% off on all plans
=> Add Happy Social Login Deal

README.md
=> VideoToBe.com

README.md
=> Add Blissbox to this joyful list of deals

README.md
Added two new deals:
QuestWiz: AI-powered customer support chatbot with GPT-4 integration
AskDocs: Smart AI document assistant with multilingual capabilities
Both deals offer significant Black Friday discounts and fit within the AI tools categories.
=> Add QuestWiz and AskDocs to Black Friday deals list

README.md, shipixen/data/config/product-overrides.js
Added draftly offer in the product list
=> feat(stack): added draftly and overrides
